spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    publisher-confirms: true
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

gecco:
  thread: ${GECCO_THREAD:50}
  interval: ${GECCO_INTERVAL:1000}
  category-id: ${GECCO_CATEGORY_ID:23,24}
  max-page: ${GECCO_MAX_PAGE:50}
