spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    publisher-confirms: true
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

download:
  base-path: ${DOWNLOAD_BASE_PATH:C:\\Users\\mayh0\\Desktop}