spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:127.0.0.1}
    port: ${RABBITMQ_PORT:5672}
    publisher-confirms: true
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true
          auth: true
    password: ${MAIL_PASSWORD:password}
    username: ${MAIL_USERNAME:mail@host.com}
    host: ${MAIL_HOST:mail.host.com}
    recipient: ${MAIL_RECIPIENT:who.mail}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false}
    username: ${DATASOURCE_USERNAME:demo}
    password: ${DATASOURCE_PASSWORD:demo}
gecco:
  thread: ${GECCO_THREAD:10}
  interval: ${GECCO_INTERVAL:1000}